#!/usr/bin/env node
// Sale scan (groundwork for sales phase 3). Reads each brand's public Shopify
// product feed and reports who has marked-down products right now.
//   node scripts/detect-sales.mjs   → writes docs/reports/sales-scan.md + .json
// Report only: nothing on the site reads this yet. To show a sale on the site,
// add a `sale: { text, until }` entry to the brand by hand.
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { ROOT, loadDesigners } from './lib/brands.mjs';

const CONCURRENCY = 6;
const TIMEOUT_MS = 25000;
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

async function scan(d) {
  let origin;
  try { origin = new URL(d.url).origin; } catch { return { name: d.name, platform: 'unknown' }; }
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(origin + '/products.json?limit=250', { signal: ctrl.signal, headers: { 'User-Agent': UA, 'Accept': 'application/json' } });
    if (!res.ok || !/json/i.test(res.headers.get('content-type') || '')) return { name: d.name, url: d.url, platform: 'other' };
    const { products } = await res.json();
    if (!Array.isArray(products)) return { name: d.name, url: d.url, platform: 'other' };
    const cuts = [];
    for (const p of products) {
      // A product counts as marked down if any variant has a higher compare-at price.
      const best = Math.max(0, ...(p.variants || []).map(v => {
        const price = parseFloat(v.price), was = parseFloat(v.compare_at_price);
        return was > price && price > 0 ? Math.round((1 - price / was) * 100) : 0;
      }));
      if (best >= 5) cuts.push(best);
    }
    cuts.sort((a, b) => a - b);
    return {
      name: d.name, url: d.url, platform: 'shopify',
      products: products.length,
      discounted: cuts.length,
      share: products.length ? Math.round(cuts.length / products.length * 100) : 0,
      median: cuts.length ? cuts[Math.floor(cuts.length / 2)] : 0,
      max: cuts.length ? cuts[cuts.length - 1] : 0,
    };
  } catch (e) {
    return { name: d.name, url: d.url, platform: 'error', detail: String(e.cause?.code || e.name) };
  } finally {
    clearTimeout(timer);
  }
}

const designers = loadDesigners();
const results = [];
let next = 0;
await Promise.all(Array.from({ length: CONCURRENCY }, async () => {
  while (next < designers.length) {
    results.push(await scan(designers[next++]));
    if (results.length % 50 === 0) console.error(`${results.length}/${designers.length}`);
  }
}));

const shopify = results.filter(r => r.platform === 'shopify');
// "On sale" here means a real share of the catalogue is marked down, not one stray item.
const onSale = shopify.filter(r => r.discounted >= 3 && r.share >= 10).sort((a, b) => b.share - a.share);
const date = new Date().toISOString().slice(0, 10);
let md = `# Sale scan — ${date}\n\n`;
md += `Read the public product feed of ${shopify.length} Shopify stores out of ${designers.length} brands `;
md += `(${results.filter(r => r.platform === 'other').length} are on another platform or keep the feed closed, ${results.filter(r => r.platform === 'error').length} errored). `;
md += `Generated by \`node scripts/detect-sales.mjs\`.\n\n`;
md += `A brand is listed when at least 3 products and 10% of its catalogue are marked down. `;
md += `The feed shows price cuts only: it has no end date, and it misses sales run through discount codes or banners. `;
md += `Check the brand's site before adding a \`sale\` entry.\n\n`;
md += `Many stores keep a permanent outlet section or permanent "was" prices, so a markdown is not the same as a sale event. `;
md += `The first group is the closest thing to a real, store-wide sale.\n`;
const tiers = [
  ['Store-wide: 80% or more of the catalogue marked down', r => r.share >= 80],
  ['Large part of the catalogue: 40–79%', r => r.share >= 40 && r.share < 80],
  ['A sale section: 10–39%', r => r.share < 40],
];
for (const [title, test] of tiers) {
  const rows = onSale.filter(test);
  md += `\n## ${title} (${rows.length})\n\n| Brand | Catalogue marked down | Typical cut | Biggest cut | Site |\n|---|---|---|---|---|\n`;
  for (const r of rows) md += `| ${r.name} | ${r.share}% (${r.discounted} of ${r.products}) | ${r.median}% | ${r.max}% | ${r.url} |\n`;
}
if (shopify.some(r => r.products === 250)) md += `\nStores with 250 products shown were only read up to their first 250.\n`;

const dir = path.join(ROOT, 'docs', 'reports');
mkdirSync(dir, { recursive: true });
writeFileSync(path.join(dir, 'sales-scan.md'), md);
writeFileSync(path.join(dir, 'sales-scan.json'), JSON.stringify(results.sort((a, b) => a.name.localeCompare(b.name)), null, 1));
console.log(`shopify ${shopify.length}/${designers.length}, on sale ${onSale.length}. Report: docs/reports/sales-scan.md`);
